// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVORdFMCmE9U-5KlQ17rMubq7ShPa-3f4',
    appId: '1:906862508246:android:15a9a85e04d7d49eff7177',
    messagingSenderId: '906862508246',
    projectId: 'fit-planner-de29a',
    storageBucket: 'fit-planner-de29a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk7JIXo8lBXV9_NCwtYxeiDzAJlhOjsrE',
    appId: '1:906862508246:ios:ff093dae06e90ba4ff7177',
    messagingSenderId: '906862508246',
    projectId: 'fit-planner-de29a',
    storageBucket: 'fit-planner-de29a.firebasestorage.app',
    androidClientId: '906862508246-aae9282o1ie1arjdp4hgeus2926ov452.apps.googleusercontent.com',
    iosClientId: '906862508246-b025p3mg51l6cvtsog4cqutj3td6rk3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.planner',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwA05SgEDJ2SRgFiehPZzAC4sm7w2x_eM',
    appId: '1:906862508246:web:61ad6bd3e88ac156ff7177',
    messagingSenderId: '906862508246',
    projectId: 'fit-planner-de29a',
    authDomain: 'fit-planner-de29a.firebaseapp.com',
    storageBucket: 'fit-planner-de29a.firebasestorage.app',
    measurementId: 'G-83ZVD7Z1MD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk7JIXo8lBXV9_NCwtYxeiDzAJlhOjsrE',
    appId: '1:906862508246:ios:ff093dae06e90ba4ff7177',
    messagingSenderId: '906862508246',
    projectId: 'fit-planner-de29a',
    storageBucket: 'fit-planner-de29a.firebasestorage.app',
    androidClientId: '906862508246-aae9282o1ie1arjdp4hgeus2926ov452.apps.googleusercontent.com',
    iosClientId: '906862508246-b025p3mg51l6cvtsog4cqutj3td6rk3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.planner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwA05SgEDJ2SRgFiehPZzAC4sm7w2x_eM',
    appId: '1:906862508246:web:87ba9e76b0d8d16dff7177',
    messagingSenderId: '906862508246',
    projectId: 'fit-planner-de29a',
    authDomain: 'fit-planner-de29a.firebaseapp.com',
    storageBucket: 'fit-planner-de29a.firebasestorage.app',
    measurementId: 'G-KYKFRKLD9V',
  );

}